### ISSUE TITLE
Duplicate in localisation file.

### ISSUE THREAD

**Issue by josdemmers** [new-world-tools/new-world-tools#1]
Just used v0.4.1 on the Brimstone update.
When parsing the results I got an exception and noticed a localisation file contained a duplicate.
Not sure if it's because of this tool or that it's because of the New World data itself.

File: javelindata_itemdefinitions_master.loc.xml
Duplicate:
```
<string key="WritofAdventure_MasterName">Writ of Adventure</string>
<string key="WritofAdventure_Description">An account of your deeds! This is a crafting material used to craft runes.</string>
<string key="WritofAdventure_MasterName">Writ of Adventure</string>
<string key="WritofAdventure_Description">An account of your deeds! This is a crafting material used to craft runes.</string>
```

**Comment by zelenin** [comment]
yes, localization files have duplicates. They are also case-insensitive. This is not new-world-tools issue. You shoiuld handle it in your parser

**Comment by josdemmers** [comment]
Ok that is good to know, thank you. First time I came across a duplicate in a localization file since working on NewWorldCompanion so wanted to be sure.
I'm only using javelindata_housingitems.loc.xml and javelindata_itemdefinitions_master.loc.xml so that might explain why I never came across any duplicates.

**Comment by zelenin** [comment]
> yes, localization files have duplicates. They are also case-insensitive. This is not new-world-tools issue. You shoiuld handle it in your parser

also, some keys have the @ prefix, some do not
