### ISSUE TITLE
Is the CraftingRecipes file deprecated?

### ISSUE THREAD

**Issue by josdemmers** [new-world-tools/new-world-tools#10]
Noticed that `CraftingRecipes.json` now results in an empty file. I was wondering if the `\datasheets\CraftingRecipeData\CraftingRecipes.json` is now deprecated and I should switch to use the files that are created per category?
Or is it a bug and should CraftingRecipes.json still contain data?

![image](https://github.com/new-world-tools/new-world-tools/assets/8627157/b6d8d8b7-a58e-4672-a2ed-436cea2bf7fd)

**Comment by zelenin** [comment]
> I was wondering if the \datasheets\CraftingRecipeData\CraftingRecipes.json is now deprecated and I should switch to use the files that are created per category?

yes
