### ISSUE TITLE
Error while extrating

### ISSUE THREAD

**Issue by adamtrip** [new-world-tools/new-world-tools#2]
Hello

I'm having this error while executing the pack extractor:
`2022/11/17 12:19:51 task #2 err: Failed to load oo2core_9_win64.dll: %1 is not a valid Win32 application.`

While executing this command:
`.\pak-extracter.exe 
    -assets "D:\New World\assets" 
    -output ".\extract" 
    -threads 10`

Any thoughts?

Thanks in advance

**Comment by zelenin** [comment]
find ```oo2core_9_win64.dll``` using google and put it in the same directory where .exe is

**Comment by adamtrip** [comment]
I've already had put the dll into the folder, however, the DLL that it downloaded was corrupt or something. Grabbed one from google and is now running like a charm. Thanks!
