### ISSUE TITLE
include exclude glob filter

### ISSUE THREAD

**Issue by giniedp** [new-world-tools/new-world-tools#4]
Wanted to use the `filter` parameter, but realized it is actually exclusive, but i needed it inclusive.
Further i'd love to filter by a glob pattern instead of file extension. Would that be possible?

I can think of two ways how this could be parameterized
Either add a `-glob` argument, where each pattern that starts with a `!` would remove a file from result
Or add two arguments `-include` and `-exclude`

Per default all files are in the resulting set.
The`-include` parameter (or `-glob` patterns without `!`) overrides the resulting set.
The `-exclude` parameter (or `-glob` patterns with `!`) remove entries from resulting set.

**Comment by zelenin** [comment]
I like the idea with the ```glob```. Need a research

**Comment by nakda** [comment]
Just a comment to share I was also scratching my head regarding filters. I initially thought I was not using it properly until I figured out that this parameter is to exclude specified extensions, while I thought it would be the opposite. 

To have both options would be great, but meanwhile I would suggest to update the documentation to make it more explicit. 

Great tool by the way!

**Comment by giniedp** [comment]
@zelenin any update in sight on this one?

**Comment by zelenin** [comment]
added exclude/include regexp filters (check Readme). Legacy extension filters will be removed in the future releases.
