### ISSUE TITLE
keep original folder structure with datasheet-converter

### ISSUE THREAD

**Issue by giniedp** [new-world-tools/new-world-tools#5]
I would like to suggest an option that would allow the datasheet converter to keep the original folder structure. 
Or even better, we could pass a template string to rewrite the final file path to our liking.

I have a tool chain that dependas on the original file and folder names. This would allow me to migrate from my own extractor/converter implementation to this tool without changing much in my chain.

**Comment by zelenin** [comment]
a good addition. it will be in the next release

**Comment by zelenin** [comment]
https://github.com/new-world-tools/new-world-tools/releases/tag/v0.5.4
