### ISSUE TITLE
Localized conversion fails: wrong expected type

### ISSUE THREAD

**Issue by nakda** [new-world-tools/new-world-tools#6]
I tried to use the `-localization` argument during a conversion, but it fails. 

Steps:

1.  Extract all pak files from the Paks folder (I only put DataStrm-part1.pak): `pak-extracter.exe -assets Paks -output Extracted\DataStrm-part1 `
2. Extract all pak files from the Paks folder (I only put server.pak): `pak-extracter.exe -assets Paks -output Extracted\server `
3. Convert datables contained in server.pak while providing localizations from DataStrm-part1: `datasheet-converter.exe -input "Extracted\server\server\sharedassets\springboardentitites\datatables" -output "Converted\server-localized" -format json -localization "Extracted\DataStrm-part1\localization\fr-fr" -keep-structure`
4. Output: 
```
2023/02/05 11:07:21 The number of threads is set to 3
2023/02/05 11:07:22 localization.New: expected element type <resources> but have <Workbook>
```

Am I doing something wrong?

Note: I extracted both pak files as a two steps process because I initially experimented with files one by one. I could have done it as a single step.

**Comment by zelenin** [comment]
the french localization contains some kind of legacy file. fixed https://github.com/new-world-tools/new-world-tools/releases/tag/v0.5.7
