### ISSUE TITLE
Question: pak file order

### ISSUE THREAD

**Issue by nakda** [new-world-tools/new-world-tools#7]
I noticed the extracter process the pak files in the following order:
```
\DataStrm-part1.pak
\DataStrm-part10.pak
\DataStrm-part11.pak
\DataStrm-part12.pak
...
\DataStrm-part19.pak
\DataStrm-part2.pak
\DataStrm-part20.pak
```

Are the pak incremental? If they are, wouldn't it mess with the version of files being unpacked (eg. file "test" contained in pak2 later updated in pak11)?

**Comment by zelenin** [comment]
all .pak files have a unique set of files, except `shadercachestartup.pak` and `shadersbin.pak`. The unpacking order is not important
